/**
 * Codevi Theme System — All 9 built-in theme definitions.
 *
 * Each theme provides:
 *  - CSS custom-property values consumed by Tailwind utility classes
 *  - A full Monaco editor theme (base, token rules, chrome colors)
 *
 * To add a new theme:
 *  1. Add its slug to `ThemeId` in `themeTypes.ts`
 *  2. Add an entry in `THEME_IDS` and `THEME_LABELS`
 *  3. Add a `ThemeDefinition` entry in the `THEMES` map below
 *  → No component changes needed.
 */

import type { ThemeDefinition, ThemeId } from "./themeTypes";

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  /* ───────────────────────────── DARK MODERN ──────────────────────────── */
  "dark-modern": {
    colorScheme: "dark",
    css: {
      canvas: "#0f1319",
      surface: "#161b24",
      surfaceRaised: "#1d2330",
      border: "#2a3242",
      fg: "#e7eaf0",
      fgMuted: "#8a93a6",
      accent: "#4fa3d1",
      accentFg: "#0f1319",
      active: "#e3a23c",
      danger: "#e0605a",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "8a93a6", fontStyle: "italic" },
        { token: "keyword", foreground: "4fa3d1" },
        { token: "keyword.control", foreground: "4fa3d1" },
        { token: "type", foreground: "56c8a7" },
        { token: "type.identifier", foreground: "56c8a7" },
        { token: "identifier", foreground: "e7eaf0" },
        { token: "variable", foreground: "e7eaf0" },
        { token: "number", foreground: "e3a23c" },
        { token: "string", foreground: "9fd18a" },
        { token: "string.escape", foreground: "d4976c" },
        { token: "operator", foreground: "c0c6d0" },
        { token: "delimiter", foreground: "c0c6d0" },
        { token: "annotation", foreground: "4fa3d1" },
      ],
      colors: {
        "editor.background": "#161b24",
        "editor.foreground": "#e7eaf0",
        "editor.lineHighlightBackground": "#1d233080",
        "editor.selectionBackground": "#4fa3d140",
        "editorLineNumber.foreground": "#5c6577",
        "editorLineNumber.activeForeground": "#e7eaf0",
        "editorCursor.foreground": "#e3a23c",
        "editorBracketMatch.background": "#4fa3d130",
        "editorBracketMatch.border": "#4fa3d160",
      },
    },
  },

  /* ───────────────────────────── LIGHT MODERN ─────────────────────────── */
  "light-modern": {
    colorScheme: "light",
    css: {
      canvas: "#eef1f5",
      surface: "#ffffff",
      surfaceRaised: "#f5f7fa",
      border: "#d7dce3",
      fg: "#1b2230",
      fgMuted: "#5c6577",
      accent: "#2e7cb8",
      accentFg: "#ffffff",
      active: "#c9821f",
      danger: "#c4453f",
    },
    monaco: {
      base: "vs",
      rules: [
        { token: "comment", foreground: "5c6577", fontStyle: "italic" },
        { token: "keyword", foreground: "2e7cb8" },
        { token: "keyword.control", foreground: "2e7cb8" },
        { token: "type", foreground: "1a7a5a" },
        { token: "type.identifier", foreground: "1a7a5a" },
        { token: "identifier", foreground: "1b2230" },
        { token: "variable", foreground: "1b2230" },
        { token: "number", foreground: "c9821f" },
        { token: "string", foreground: "3f7d3f" },
        { token: "string.escape", foreground: "a65d00" },
        { token: "operator", foreground: "3a4250" },
        { token: "delimiter", foreground: "3a4250" },
        { token: "annotation", foreground: "2e7cb8" },
      ],
      colors: {
        "editor.background": "#ffffff",
        "editor.foreground": "#1b2230",
        "editor.lineHighlightBackground": "#f5f7fa",
        "editor.selectionBackground": "#2e7cb830",
        "editorLineNumber.foreground": "#8a93a6",
        "editorLineNumber.activeForeground": "#1b2230",
        "editorCursor.foreground": "#c9821f",
        "editorBracketMatch.background": "#2e7cb825",
        "editorBracketMatch.border": "#2e7cb850",
      },
    },
  },

  /* ──────────────────────────── ONE DARK PRO ──────────────────────────── */
  "one-dark-pro": {
    colorScheme: "dark",
    css: {
      canvas: "#21252b",
      surface: "#282c34",
      surfaceRaised: "#2c313a",
      border: "#3e4451",
      fg: "#abb2bf",
      fgMuted: "#6b7280",
      accent: "#61afef",
      accentFg: "#21252b",
      active: "#d19a66",
      danger: "#e06c75",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "5c6370", fontStyle: "italic" },
        { token: "keyword", foreground: "c678dd" },
        { token: "keyword.control", foreground: "c678dd" },
        { token: "type", foreground: "e5c07b" },
        { token: "type.identifier", foreground: "e5c07b" },
        { token: "identifier", foreground: "e06c75" },
        { token: "variable", foreground: "e06c75" },
        { token: "number", foreground: "d19a66" },
        { token: "string", foreground: "98c379" },
        { token: "string.escape", foreground: "56b6c2" },
        { token: "operator", foreground: "56b6c2" },
        { token: "delimiter", foreground: "abb2bf" },
        { token: "annotation", foreground: "61afef" },
      ],
      colors: {
        "editor.background": "#282c34",
        "editor.foreground": "#abb2bf",
        "editor.lineHighlightBackground": "#2c313a80",
        "editor.selectionBackground": "#3e4451",
        "editorLineNumber.foreground": "#4b5263",
        "editorLineNumber.activeForeground": "#abb2bf",
        "editorCursor.foreground": "#528bff",
        "editorBracketMatch.background": "#61afef30",
        "editorBracketMatch.border": "#61afef60",
      },
    },
  },

  /* ──────────────────────────── GITHUB DARK ───────────────────────────── */
  "github-dark": {
    colorScheme: "dark",
    css: {
      canvas: "#0d1117",
      surface: "#161b22",
      surfaceRaised: "#1c2128",
      border: "#30363d",
      fg: "#e6edf3",
      fgMuted: "#8b949e",
      accent: "#58a6ff",
      accentFg: "#0d1117",
      active: "#d29922",
      danger: "#f85149",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "8b949e", fontStyle: "italic" },
        { token: "keyword", foreground: "ff7b72" },
        { token: "keyword.control", foreground: "ff7b72" },
        { token: "type", foreground: "ffa657" },
        { token: "type.identifier", foreground: "ffa657" },
        { token: "identifier", foreground: "e6edf3" },
        { token: "variable", foreground: "e6edf3" },
        { token: "number", foreground: "79c0ff" },
        { token: "string", foreground: "a5d6ff" },
        { token: "string.escape", foreground: "79c0ff" },
        { token: "operator", foreground: "ff7b72" },
        { token: "delimiter", foreground: "e6edf3" },
        { token: "annotation", foreground: "58a6ff" },
      ],
      colors: {
        "editor.background": "#161b22",
        "editor.foreground": "#e6edf3",
        "editor.lineHighlightBackground": "#1c212880",
        "editor.selectionBackground": "#264f78",
        "editorLineNumber.foreground": "#6e7681",
        "editorLineNumber.activeForeground": "#e6edf3",
        "editorCursor.foreground": "#58a6ff",
        "editorBracketMatch.background": "#58a6ff25",
        "editorBracketMatch.border": "#58a6ff55",
      },
    },
  },

  /* ──────────────────────────── TOKYO NIGHT ───────────────────────────── */
  "tokyo-night": {
    colorScheme: "dark",
    css: {
      canvas: "#1a1b26",
      surface: "#1f2335",
      surfaceRaised: "#24283b",
      border: "#3b4261",
      fg: "#c0caf5",
      fgMuted: "#565f89",
      accent: "#7aa2f7",
      accentFg: "#1a1b26",
      active: "#e0af68",
      danger: "#f7768e",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "565f89", fontStyle: "italic" },
        { token: "keyword", foreground: "bb9af7" },
        { token: "keyword.control", foreground: "bb9af7" },
        { token: "type", foreground: "2ac3de" },
        { token: "type.identifier", foreground: "2ac3de" },
        { token: "identifier", foreground: "c0caf5" },
        { token: "variable", foreground: "c0caf5" },
        { token: "number", foreground: "ff9e64" },
        { token: "string", foreground: "9ece6a" },
        { token: "string.escape", foreground: "89ddff" },
        { token: "operator", foreground: "89ddff" },
        { token: "delimiter", foreground: "c0caf5" },
        { token: "annotation", foreground: "7aa2f7" },
      ],
      colors: {
        "editor.background": "#1f2335",
        "editor.foreground": "#c0caf5",
        "editor.lineHighlightBackground": "#24283b80",
        "editor.selectionBackground": "#364a82",
        "editorLineNumber.foreground": "#3b4261",
        "editorLineNumber.activeForeground": "#c0caf5",
        "editorCursor.foreground": "#c0caf5",
        "editorBracketMatch.background": "#7aa2f730",
        "editorBracketMatch.border": "#7aa2f760",
      },
    },
  },

  /* ─────────────────────────── CATPPUCCIN MOCHA ───────────────────────── */
  "catppuccin-mocha": {
    colorScheme: "dark",
    css: {
      canvas: "#1e1e2e",
      surface: "#181825",
      surfaceRaised: "#313244",
      border: "#45475a",
      fg: "#cdd6f4",
      fgMuted: "#6c7086",
      accent: "#89b4fa",
      accentFg: "#1e1e2e",
      active: "#f9e2af",
      danger: "#f38ba8",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "6c7086", fontStyle: "italic" },
        { token: "keyword", foreground: "cba6f7" },
        { token: "keyword.control", foreground: "cba6f7" },
        { token: "type", foreground: "f9e2af" },
        { token: "type.identifier", foreground: "f9e2af" },
        { token: "identifier", foreground: "cdd6f4" },
        { token: "variable", foreground: "cdd6f4" },
        { token: "number", foreground: "fab387" },
        { token: "string", foreground: "a6e3a1" },
        { token: "string.escape", foreground: "f2cdcd" },
        { token: "operator", foreground: "89dceb" },
        { token: "delimiter", foreground: "9399b2" },
        { token: "annotation", foreground: "89b4fa" },
      ],
      colors: {
        "editor.background": "#181825",
        "editor.foreground": "#cdd6f4",
        "editor.lineHighlightBackground": "#31324480",
        "editor.selectionBackground": "#585b7040",
        "editorLineNumber.foreground": "#45475a",
        "editorLineNumber.activeForeground": "#cdd6f4",
        "editorCursor.foreground": "#f5e0dc",
        "editorBracketMatch.background": "#89b4fa30",
        "editorBracketMatch.border": "#89b4fa60",
      },
    },
  },

  /* ─────────────────────────────── DRACULA ────────────────────────────── */
  dracula: {
    colorScheme: "dark",
    css: {
      canvas: "#282a36",
      surface: "#21222c",
      surfaceRaised: "#343746",
      border: "#44475a",
      fg: "#f8f8f2",
      fgMuted: "#6272a4",
      accent: "#bd93f9",
      accentFg: "#282a36",
      active: "#f1fa8c",
      danger: "#ff5555",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "6272a4", fontStyle: "italic" },
        { token: "keyword", foreground: "ff79c6" },
        { token: "keyword.control", foreground: "ff79c6" },
        { token: "type", foreground: "8be9fd", fontStyle: "italic" },
        { token: "type.identifier", foreground: "8be9fd", fontStyle: "italic" },
        { token: "identifier", foreground: "f8f8f2" },
        { token: "variable", foreground: "f8f8f2" },
        { token: "number", foreground: "bd93f9" },
        { token: "string", foreground: "f1fa8c" },
        { token: "string.escape", foreground: "ff79c6" },
        { token: "operator", foreground: "ff79c6" },
        { token: "delimiter", foreground: "f8f8f2" },
        { token: "annotation", foreground: "8be9fd" },
      ],
      colors: {
        "editor.background": "#21222c",
        "editor.foreground": "#f8f8f2",
        "editor.lineHighlightBackground": "#34374680",
        "editor.selectionBackground": "#44475a",
        "editorLineNumber.foreground": "#6272a4",
        "editorLineNumber.activeForeground": "#f8f8f2",
        "editorCursor.foreground": "#f8f8f2",
        "editorBracketMatch.background": "#bd93f930",
        "editorBracketMatch.border": "#bd93f960",
      },
    },
  },

  /* ──────────────────────────────── NORD ──────────────────────────────── */
  nord: {
    colorScheme: "dark",
    css: {
      canvas: "#2e3440",
      surface: "#3b4252",
      surfaceRaised: "#434c5e",
      border: "#4c566a",
      fg: "#eceff4",
      fgMuted: "#8490a5",
      accent: "#88c0d0",
      accentFg: "#2e3440",
      active: "#ebcb8b",
      danger: "#bf616a",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "616e88", fontStyle: "italic" },
        { token: "keyword", foreground: "81a1c1" },
        { token: "keyword.control", foreground: "81a1c1" },
        { token: "type", foreground: "8fbcbb" },
        { token: "type.identifier", foreground: "8fbcbb" },
        { token: "identifier", foreground: "eceff4" },
        { token: "variable", foreground: "eceff4" },
        { token: "number", foreground: "b48ead" },
        { token: "string", foreground: "a3be8c" },
        { token: "string.escape", foreground: "ebcb8b" },
        { token: "operator", foreground: "81a1c1" },
        { token: "delimiter", foreground: "d8dee9" },
        { token: "annotation", foreground: "5e81ac" },
      ],
      colors: {
        "editor.background": "#3b4252",
        "editor.foreground": "#eceff4",
        "editor.lineHighlightBackground": "#434c5e80",
        "editor.selectionBackground": "#4c566a",
        "editorLineNumber.foreground": "#616e88",
        "editorLineNumber.activeForeground": "#d8dee9",
        "editorCursor.foreground": "#d8dee9",
        "editorBracketMatch.background": "#88c0d030",
        "editorBracketMatch.border": "#88c0d060",
      },
    },
  },

  /* ──────────────────────────── AYU MIRAGE ────────────────────────────── */
  "ayu-mirage": {
    colorScheme: "dark",
    css: {
      canvas: "#1f2430",
      surface: "#232834",
      surfaceRaised: "#2a2f3e",
      border: "#3d4455",
      fg: "#cbccc6",
      fgMuted: "#707a8c",
      accent: "#73d0ff",
      accentFg: "#1f2430",
      active: "#ffad66",
      danger: "#f28779",
    },
    monaco: {
      base: "vs-dark",
      rules: [
        { token: "comment", foreground: "5c6773", fontStyle: "italic" },
        { token: "keyword", foreground: "ffa759" },
        { token: "keyword.control", foreground: "ffa759" },
        { token: "type", foreground: "73d0ff" },
        { token: "type.identifier", foreground: "73d0ff" },
        { token: "identifier", foreground: "cbccc6" },
        { token: "variable", foreground: "cbccc6" },
        { token: "number", foreground: "ffcc66" },
        { token: "string", foreground: "bae67e" },
        { token: "string.escape", foreground: "95e6cb" },
        { token: "operator", foreground: "f29e74" },
        { token: "delimiter", foreground: "cbccc6" },
        { token: "annotation", foreground: "5ccfe6" },
      ],
      colors: {
        "editor.background": "#232834",
        "editor.foreground": "#cbccc6",
        "editor.lineHighlightBackground": "#2a2f3e80",
        "editor.selectionBackground": "#34455a",
        "editorLineNumber.foreground": "#5c6773",
        "editorLineNumber.activeForeground": "#cbccc6",
        "editorCursor.foreground": "#ffcc66",
        "editorBracketMatch.background": "#73d0ff30",
        "editorBracketMatch.border": "#73d0ff60",
      },
    },
  },
};
